beta: main.go
	docker run \
	-v /Users/iansmith/machineroom.src/beta:/go/src/github.com/igneous-systems/beta \
	gotooling:0.0.1 \
	go build -o /go/src/github.com/igneous-systems/beta/beta \
		/go/src/github.com/igneous-systems/beta/main.go