alpha: main.go
	docker run \
	-v /Users/iansmith/machineroom.src/alpha:/go/src/github.com/igneous-systems/alpha \
	gotooling:0.0.1 \
	go build -o /go/src/github.com/igneous-systems/alpha/alpha \
		/go/src/github.com/igneous-systems/alpha/main.go